mkdocs.yml
=> PG-491 Fixed repo name in mkdocs config

docs/configuration.md, docs/reference.md, mkdocs.yml
modified:   docs/configuration.md
modified:   docs/reference.md
=> PG-479 Added PGSM views for every PG version

docs/release_notes.md
modified:   docs/release_notes.md
=> PG-481 Release notes 1.1.0

docs/release_notes.md
modified:   docs/release_notes.md
=> PG-517 Fixed the issue list formatting

docs/index.md, docs/install.md, docs/reference.md, docs/release_notes.md
Updated the release notes for 1.1.1
modified:   docs/index.md
modified:   docs/install.md
modified:   docs/reference.md
modified:   docs/release_notes.md
=> PG-463 Added support of PG 15 to the docs.

docs/configuration.md
Updated the default value for pgsm_enable_query_plan and pgsm_track_planning from 0 to no.
=> Update to configuration.md.

docs/configuration.md
=> PG-538 Updated the server restart policy for que

docs/configuration.md, docs/user_guide.md
Fixed usage example
modified:   docs/configuration.md
modified:   docs/user_guide.md
=> PG-312 Updated histogram configuration default values

docs/release_notes.md
Signed-off-by: Kai Wagner <kai.wagner@percona.com>
=> PG-528: Updated release notes and added a date and PG15 support

docs/upgrade.md, mkdocs.yml
=> PG-598 Upgrade instructions

docs/configuration.md
Updated the  pgsm_enable_overflow description
=> PG-606 Added pgsm_query_id to configuratio

docs/configuration.md, docs/reference.md, docs/user_guide.md, mkdocs.yml
Merged examples with feature descriptions
=> Updated user guide doc

_resource/overrides/main.html
modified:   _resource/overrides/main.html
=> PG-617 Updated Google Tag manager for the docs

_resource/overrides/main.html, mkdocs.yml, requirements-doc.txt
modified:   mkdocs-base.yml
modified:   overrides/main.html
modified:   requirements.txt
=> Adding text snippets to link previews

docs/release-notes/2.0.1.md, docs/release-notes/release_notes.md, mkdocs.yml, variables.yml
new file:   docs/release-notes/2.0.1.md
modified:   docs/release-notes/release_notes.md
=> PG-627 Release notes 2.0.1

mkdocs.yml
=> Side TOC contains duplicated Release notes section

docs/copyright.md, docs/trademark-policy.md, mkdocs.yml
new file:   docs/copyrighting-and-licensing.md
new file:   docs/trademark-policy.md
=> DOCS-72 Update Trademark Policy, Copyright and Licensing Information

docs/upgrade.md
=> PG-639 Added the step to update the package

_resource/overrides/main.html, docs/css/extra.css, mkdocs.yml
modified:   _resource/overrides/main.html
new file:   docs/css/extra.css
=> DOCS-87 Added pixel to docs

docs/auto-enable.md, docs/reference.md, docs/setup.md, mkdocs.yml
new file:   docs/auto-enable.md
modified:   docs/setup.md
=> Auto-create pgsm for new dbs

_resource/overrides/main.html
modified:   _resource/overrides/main.html
=> DISTPG-918 Added PostHog for docs

docs/configuration.md, docs/setup.md
[PG-644](https://perconadev.atlassian.net/browse/PG-644)
Related code changes: https://github.com/percona/pg_stat_monitor/pull/469
[PG-644]: https://perconadev.atlassian.net/browse/PG-644?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PG-644] Add pgsm_track_application_names parameter description

docs/release-notes/2.1.0.md, docs/release-notes/release_notes.md, mkdocs.yml, variables.yml
new file:   docs/release-notes/2.1.0.md
modified:   docs/release-notes/release_notes.md
modified:   variables.yml
=> PG-930 Release notes 2.1.0

docs/reference.md
=> PG-1352 Updated the rows filed description in view reference

docs/configuration.md
SERVER RESTART changed from NO to YES
=> Fix for DOCS-50

README.md, docs/release-notes/2.2.0.md, docs/release-notes/release_notes.md, mkdocs.yml, variables.yml
date variables added, updated ToC to include new 2.2.0 rn file
=> PG-1702-Release-notes-2.2.0

README.md, docs/comparison.md, docs/functions.md, docs/index.md, docs/reference.md
[PG-1907](https://perconadev.atlassian.net/browse/PG-1907)
Add information related to PostgreSQL 18 in documentation.
[PG-1907]: https://perconadev.atlassian.net/browse/PG-1907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PG-1907 Add PostgreSQL 18 realted info
